# Generated by Django 4.0 on 2022-01-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_payment_profile_alter_profile_mobile'),
        ('accounts', '0002_alter_payment_profile_alter_profile_mobile_and_more'),
    ]

    operations = [
    ]
